### PR TITLE
Fix issue with class methods and adds coverage.

### PR DESCRIPTION
**Pull request by etagwerker**
Hey,

This fixes issue #29. 

Please check it out and let me know if it looks fine.

Thanks!

### CODE REVIEW

**Comment by zenspider** [comment]
OK. I figured out the problem I was having trying to repro against my client's code. PEBCAK. This repro and fix look good to me. I'm gonna tweak the fix a bit to match my style more...

**Comment by zenspider** [comment]
Fixed. Thanks everyone!

**Comment by zenspider** [comment]
This is scheduled to be released on 12/13, but I think I'm going to bump it up.

**Comment by tleish** [comment]
It doesn't appear this update has been released yet.  Is there a new date?

**Pull request closed without merging**
